// <auto-generated />
namespace my_project_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditeJobmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditeJobmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201807061642458_EditeJobmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
